### ISSUE TITLE
correlation-id cannot always be found from different thread

### ISSUE THREAD

**Issue by Jiehong** [bobbui/json-logging-python#60]
Hi,

I'm currently getting the following error for some cases:

```
Call stack:
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
(...)
    self.logger.error(f"{message}")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/.local/share/virtualenvs/working_dir-WB6aV072/lib/python3.8/site-packages/json_logging/__init__.py", line 243, in format
    log_object = self._format_log_object(record, request_util=_request_util)
  File "/.local/share/virtualenvs/working_dir-WB6aV072/lib/python3.8/site-packages/json_logging/__init__.py", line 341, in _format_log_object
    "correlation_id": request_util.get_correlation_id(within_formatter=True),
  File "/.local/share/virtualenvs/working_dir-WB6aV072/lib/python3.8/site-packages/json_logging/util.py", line 143, in get_correlation_id
    correlation_id = self.request_adapter.get_correlation_id_in_request_context(request)
  File "/.local/share/virtualenvs/working_dir-WB6aV072/lib/python3.8/site-packages/json_logging/framework/connexion/__init__.py", line 93, in get_correlation_id_in_request_context
    return _connexion.g.get('correlation_id', None)
  File "/.local/share/virtualenvs/working_dir-WB6aV072/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/.local/share/virtualenvs/working_dir-WB6aV072/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/.local/share/virtualenvs/working_dir-WB6aV072/lib/python3.8/site-packages/flask/globals.py", line 45, in _lookup_app_object
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
```

But not all requests suffer from this issue (strangely).

This code takes a method from a class (here named `func`), and run it in different threads, as such:

```python
    with ThreadPoolExecutor(max_workers=number_of_workers) as executor:
        return executor.map(func, iterable)
```

But the logger for that instance of the class is pre-created in advance, but it seems that python is trying to re-create it when passed to the thread? That's my guess.

And then this error occurs.

Any idea how to fix this?

**Comment by bobbui** [comment]
unfortunately, this is a know limitation of the library, correlation is either stored in thread-local storage or extract from the call stack given the logging statement is invoked in the same call stack as the main request controller. what you can do is explicitly pass correlation-id into the executor map function

**Comment by Jiehong** [comment]
@bobbui : how can I pass the correlation id to the executor instance so that it is found by json_logging?

Should I set it via a contextvars (https://docs.python.org/3/library/contextvars.html), or am I supposed to make a wrapper to `getLogger` taking a correlation-id to manually set it?

**Comment by bobbui** [comment]
@Jiehong correlation can be obtained like this:
```
correlation_id = json_logging.get_correlation_id(request=request)
```
then pass args to executor.map , some guidance from here: https://stackoverflow.com/questions/6785226/pass-multiple-parameters-to-concurrent-futures-executor-map
